DROP DATABASE IF EXISTS timetable;
CREATE DATABASE timetable;
USE timetable;

CREATE TABLE timetable (
	id INT NOT NULL AUTO_INCREMENT,
    course VARCHAR(100) ,
    course_desc VARCHAR(100) ,
    campus VARCHAR(100) ,
    unit VARCHAR(100) ,
    unit_desc VARCHAR(100) ,
    hours INTEGER ,
    semester INTEGER ,
    room VARCHAR(100) ,
    lecturer VARCHAR(100),
	room_lock VARCHAR(100),
	day_lock VARCHAR(100),
	time_lock VARCHAR(100),
	PRIMARY KEY (id)
);
-- SHOW TABLES;
-- DESCRIBE timetable;

insert into timetable (course, course_desc, campus, unit, unit_desc, hours, semester, room, lecturer, room_lock, day_lock, time_lock) values
("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp B","STB","CSCOMM","Core Skills Comms","2","1","A","0","BF45","Wednesday","09:00")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","WESTWING","CSCOMM","Core Skills Comms","2","1","A","NLR","H1.08","Tuesday","11:00")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp B","WESTWING","CSCOMM","Core Skills Comms","2","1","A","NLR","H1.08","Wednesday","11:00")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","CSCOMM","Core Skills Comms","2","1","A","NLR","S3.12","Tuesday","09:00")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","CSCOMM","Core Skills Comms","2","1","A","NLR","BF45","Wednesday","11:00")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp B","STB","CSCOMM","Core Skills Comms","2","1","A","NLR","BF45","Thursday","11:00")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","WESTWING","CSCOMM","Core Skills Comms","2","1","A","NLR","H1.08","Wednesday","09:00")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp B","WESTWING","CSCOMM","Core Skills Comms","2","1","A","NLR","H1.08","Thursday","09:00")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","CSNUM","Core Skills Numeracy","2","2","A","NLR","BF45","Tuesday","09:00")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp B","STB","CSNUM","Core Skills Numeracy","2","2","A","0","BF45","Wednesday","09:00")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","WESTWING","CSNUM","Core Skills Numeracy","2","2","A","NLR","H1.08","Tuesday","11:00")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp B","WESTWING","CSNUM","Core Skills Numeracy","2","2","A","NLR","H1.08","Wednesday","11:00")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","CSNUM","Core Skills Numeracy","2","2","A","NLR","S3.12","Tuesday","09:00")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","CSNUM","Core Skills Numeracy","2","2","A","NLR","BF45","Wednesday","11:00")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp B","STB","CSNUM","Core Skills Numeracy","2","2","A","NLR","BF45","Thursday","11:00")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","WESTWING","CSNUM","Core Skills Numeracy","2","2","A","NLR","H1.08","Wednesday","09:00")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp B","WESTWING","CSNUM","Core Skills Numeracy","2","2","A","NLR","H1.08","Thursday","09:00")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("BSAPN_BF117A","BSc Applied Networking Technologies SCQF Level 9 - Yr1 Grp A","STB","CMP394","Cyber Security","3","1","BF45A","Pele10","0","0","0")
,("BSAPN_BF117A","BSc Applied Networking Technologies SCQF Level 9 - Yr1 Grp A","STB","CMP391","Cloud Computing + Virtualisation","3","2","BF45A","Pele10","0","0","0")
,("BSAPN_BF117A","BSc Applied Networking Technologies SCQF Level 9 - Yr1 Grp A","STB","CMP392","Computer Forensics","3","2","BF45A","Messi","0","0","0")
,("BSAPN_BF117A","BSc Applied Networking Technologies SCQF Level 9 - Yr1 Grp A","STB","CMP393","Computer Network Group Project","3","2","BF45A","Ronal","0","0","0")
,("BSAPN_BF117A","BSc Applied Networking Technologies SCQF Level 9 - Yr1 Grp A","STB","CMP395","Managing Computer Network Projects","3","1","BF45A","Ronal","0","0","0")
,("BSAPN_BF117A","BSc Applied Networking Technologies SCQF Level 9 - Yr1 Grp A","STB","CMP396","Network Technologies","3","1","BF45A","Pele10","0","0","0")
,("BSAPN_BF117A","BSc Applied Networking Technologies SCQF Level 9 - Yr1 Grp A","STB","CMPIL1","Independent Learning S1","3","1","BF45A","NLR","0","0","0")
,("BSAPN_BF117A","BSc Applied Networking Technologies SCQF Level 9 - Yr1 Grp A","STB","CMPIL2","Independent Learning S2","3","2","BF45A","NLR","0","0","0")
,("HCCPT7_SD117A","HNC Computing (Schools) SCQF Level 7 - Yr1 Grp A","EASTERN","H17334","Developing Software:  Introduction","0","0","S3.12","Neymar9","0","0","0")
,("HCCPT7_SD117A","HNC Computing (Schools) SCQF Level 7 - Yr1 Grp A","EASTERN","H17X34","Software Development:  Programming Foundations","0","0","S3.12","Neymar9","0","0","0")
,("HCCPT7_SD117A","HNC Computing (Schools) SCQF Level 7 - Yr1 Grp A","EASTERN","H17734","Troubleshooting Computer Problems","0","0","S3.12","Neymar9","0","0","0")
,("HCCPT7_SD117A","HNC Computing (Schools) SCQF Level 7 - Yr1 Grp A","EASTERN","H18134","Systems Development:  Testing Software","0","0","S3.12","Neymar9","0","0","0")
,("HCCPT7_SD117A","HNC Computing (Schools) SCQF Level 7 - Yr1 Grp A","EASTERN","H17534","Computer Systems Fundamentals","0","0","S3.12","Bob","0","0","0")
,("HCCPT7_SD117A","HNC Computing (Schools) SCQF Level 7 - Yr1 Grp A","EASTERN","H17934","Cloud Computing","0","0","S3.12","Bob","0","0","0")
,("HCCPT7_SD117A","HNC Computing (Schools) SCQF Level 7 - Yr1 Grp A","EASTERN","H18034","Systems Development:  Introduction","0","0","S3.12","Bob","0","0","0")
,("HCCPT7_SD217A","HNC Computing (Schools) SCQF Level 7 - Yr2 Grp A","EASTERN","F1VV34","Interactive Media: User Interface Design","0","0","A","Becks","0","0","0")
,("HCCPT7_SD217A","HNC Computing (Schools) SCQF Level 7 - Yr2 Grp A","EASTERN","H17834","Team Working in Computing","0","0","A","Neymar9","0","0","0")
,("HCCPT7_SD217A","HNC Computing (Schools) SCQF Level 7 - Yr2 Grp A","EASTERN","H1F734","Professionalism and Ethics in Computing","0","0","A","Becks","0","0","0")
,("HCCPT7_SD217A","HNC Computing (Schools) SCQF Level 7 - Yr2 Grp A","EASTERN","H1J834","Computing:  Graded Unit 1","0","0","A","Neymar9","0","0","0")
,("HCCPT7_SD217A","HNC Computing (Schools) SCQF Level 7 - Yr2 Grp A","EASTERN","H16W35","Relational Database Management Systems","0","0","A","Neymar9","0","0","0")
,("HCCPT7_SD217A","HNC Computing (Schools) SCQF Level 7 - Yr2 Grp A","EASTERN","H17W34","Software Development:  Developing Small Scale Standalone Applications","0","0","A","Becks","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H17334              ","Developing Software: Introduction","2","1","A","Maradona","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H17534              ","Computer Systems Fundamentals","2","1","A","Pele10","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H17734              ","Troubleshooting Computer Problems","2","1","V","Kaka7","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H17834              ","Team Working in Computing","2","2","A","Kaka7","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H17934              ","Cloud Computing","2","2","A","Zidane","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H17E34              ","Computing: PC Hardware and Operating System Essentials","2","1","CISCO","Zidane","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H17F34              ","Computing: PC Hardware and Operating System Support","2","2","CISCO","Zidane","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H1F734              ","Professionalism and Ethics in Computing","2","1","BS50","John","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","FR2435              ","Networking Technology","3","1","CISCO","John","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","FR2435              ","Networking Technology","1","1","CISCO","NLR","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H17S34              ","Network Concepts","4","2","CISCO","John","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","FR2235","Routing Technology","3","2","CISCO","John","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","FR2236","Routing Technology","1","2","CISCO","NLR","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H1J834","Computing:  Graded Unit 1","1","1","A","Pele10","0","0","0")
,("HDCON_BF117A","HND Computing: Networking SCQF Level 8 - Yr1 Grp A","STB","H1J834","Computing:  Graded Unit 1","1","2","A","Pele10","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H17334              ","Developing Software: Introduction","2","1","A","Maradona","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H17534              ","Computer Systems Fundamentals","2","1","A","Pele10","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H17734              ","Troubleshooting Computer Problems","2","1","V","Pele10","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H17834              ","Team Working in Computing","2","2","A","Maradona","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H17934              ","Cloud Computing","2","2","A","Pele10","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H17E34              ","Computing: PC Hardware and Operating System Essentials","2","1","CISCO","Pele10","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H17F34              ","Computing: PC Hardware and Operating System Support","2","2","CISCO","Pele10","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H1F734              ","Professionalism and Ethics in Computing","2","1","BS50","Messi","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","FR2435              ","Networking Technology","3","1","CISCO","John","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","FR2435              ","Networking Technology","1","1","CISCO","NLR","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H17S34              ","Network Concepts","4","2","CISCO","Pele10","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","FR2235","Routing Technology","3","2","CISCO","John","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","FR2236","Routing Technology","1","2","CISCO","NLR","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H1J834","Computing:  Graded Unit 1","1","1","A","Pele10","0","0","0")
,("HDCON_BF117B","HND Computing: Networking SCQF Level 8 - Yr1 Grp B","STB","H1J834","Computing:  Graded Unit 1","1","2","A","Pele10","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","F1W034              ","Project Management for IT","2","1","BS50","Bob","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","H17M34              ","Intrusion Prevention Systems","2","2","V","Bob","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","H8N535              ","Private Cloud Virtualisation","2","2","V","Pele10","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","H1EM34         ","Client Operating Systems","4","1","V","John","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","FR2335              ","Switching Technology","3","1","CISCO","Gullit ","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","FR2335              ","Switching Technology","1","1","CISCO","NLR","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","FR2535              ","Internetworking Technology","3","2","CISCO","Gullit ","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","FR2535              ","Internetworking Technology","1","2","CISCO","NLR","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","H16X35              ","Server Administration","2","1","V","Zidane","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","H17V34              ","Security Concepts","2","1","V","Zidane","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","H17V34+H16X35             ","Security Concepts + Server Admin","4","2","V","Zidane","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","H48V35              ","Computing: Networking: Graded Unit 2","2","1","V","Zidane","0","0","0")
,("HDCON_BF217A","HND Computing: Networking SCQF Level 8 - Yr2 Grp A","STB","H48V35              ","Computing: Networking: Graded Unit 2","2","2","V","Zidane","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","F1VV34              ","Interactive Media: User Interface Design","2","2","A","Pirlo","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H17334              ","Developing Software: Introduction","2","1","A","Ronal","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H17534              ","Computer Systems Fundamentals","2","1","A","Pele10","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H17734              ","Troubleshooting Computer Problems","2","1","A","Ronal","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H17834              ","Team Working in Computing","2","2","A","Maradona","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H17X34              ","Software Development: Programming Foundations","2","2","V","Becks","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H18034              ","Systems Development: Introduction","2","2","A","Neymar9","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H18134              ","Systems Development: Testing Software","2","1","A","Ronal","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H1F734              ","Professionalism and Ethics in Computing","2","1","BS50","Ronal","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H1J834              ","Computing: Graded Unit 1","1","1","BF47","VPG","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H1J834              ","Computing: Graded Unit 1","1","2","BF47","VPG","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H17934","Cloud Computing","2","2","A","Maradona","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H16W35              ","Relational Database Management Systems","2","1","A","Maradona","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H16W35              ","Relational Database Management Systems","2","2","A","Maradona","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H17W34              ","Software Development: Developing Small Scale Standalone Applications","2","1","A","Becks","0","0","0")
,("HDCSD_BF117A","HND Computing: Software Development SCQF Level 8 - Yr1 Grp A","STB","H17W34              ","Software Development: Developing Small Scale Standalone Applications","2","2","A","Becks","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","F1VV34              ","Interactive Media: User Interface Design","2","2","A","Pirlo","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H17334              ","Developing Software: Introduction","2","1","A","Becks","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H17534              ","Computer Systems Fundamentals","2","1","A","Bob","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H17734              ","Troubleshooting Computer Problems","2","1","A","Becks","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H17834              ","Team Working in Computing","2","2","A","Maradona","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H17X34              ","Software Development: Programming Foundations","2","2","A","Becks","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H18034              ","Systems Development: Introduction","2","2","A","Neymar9","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H18134              ","Systems Development: Testing Software","2","1","A","Becks","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H1F734              ","Professionalism and Ethics in Computing","2","1","BS50","Maradona","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H1J834              ","Computing: Graded Unit 1","1","1","A","Ronal","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H1J834              ","Computing: Graded Unit 1","1","2","A","Ronal","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H17934","Cloud Computing","2","2","BF47","VPG","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H16W35              ","Relational Database Management Systems","2","1","BF47","VPG","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H16W35              ","Relational Database Management Systems","2","2","BF47","VPG","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H17W34              ","Software Development: Developing Small Scale Standalone Applications","2","1","A","Becks","0","0","0")
,("HDCSD_BF117B","HND Computing: Software Development SCQF Level 8 - Yr1 Grp B","STB","H17W34              ","Software Development: Developing Small Scale Standalone Applications","2","2","A","Becks","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","F1VV34              ","Interactive Media: User Interface Design","2","2","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H17334              ","Developing Software: Introduction","2","1","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H17534              ","Computer Systems Fundamentals","2","1","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H17734              ","Troubleshooting Computer Problems","2","1","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H17834              ","Team Working in Computing","2","2","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H17X34              ","Software Development: Programming Foundations","2","2","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H18034              ","Systems Development: Introduction","2","2","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H18134              ","Systems Development: Testing Software","2","1","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H1F734              ","Professionalism and Ethics in Computing","2","1","BS50","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H1J834              ","Computing: Graded Unit 1","1","1","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H1J834              ","Computing: Graded Unit 1","1","2","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H17934","Cloud Computing","2","2","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H16W35              ","Relational Database Management Systems","2","1","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H16W35              ","Relational Database Management Systems","2","2","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H17W34              ","Software Development: Developing Small Scale Standalone Applications","2","1","A","0","0","0","0")
,("HDCSD_BF117C","HND Computing: Software Development SCQF Level 8 - Yr1 Grp C","STB","H17W34              ","Software Development: Developing Small Scale Standalone Applications","2","2","A","0","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","H17R35              ","Mobile Technology","2","2","V","Neymar9","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","F6C235              ","Web Development: Dynamically Generated Content","2","1","BF47","VPG","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","F6C235              ","Web Development: Dynamically Generated Content","2","2","BF47","VPG","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","H16Y35              ","Software Development: Data Structures","4","2","V","Ronal","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","H17135              ","Software Development: Object Oriented Programming","4","1","A","Neymar9","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","H17235              ","Systems Development: Object Oriented Analysis and Design","4","1","A","Neymar9","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","H48W35              ","Computing: Software Development: Graded Unit 2","4","2","A","Neymar9","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","HL9X35","Software Development: Object Oriented Programming - Advanced Concepts","2","1","A","Neymar9","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","HL9W35","Software Development: Web Development Advanced Web Scripting Concepts","1","1","BF47","VPG","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","HL9W35","Software Development: Web Development Advanced Web Scripting Concepts","1","2","BF47","VPG","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","HL9V35","Software Development: Programming Paradigms","2","1","V","Ronal","0","0","0")
,("HDCSD_BF217A","HND Computing: Software Development SCQF Level 8 - Yr2 Grp A","STB","HL9T35","Software Development: Data Structures and Performance","2","2","V","Ronal","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","H17R35              ","Mobile Technology","2","2","BF47","VPG","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","F6C235              ","Web Development: Dynamically Generated Content","2","1","A","Neymar9","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","F6C235              ","Web Development: Dynamically Generated Content","2","2","A","Neymar9","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","H16Y35              ","Software Development: Data Structures","4","2","V","Ronal","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","H17135              ","Software Development: Object Oriented Programming","4","1","BF47","VPG","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","H17235              ","Systems Development: Object Oriented Analysis and Design","4","1","BF47","VPG","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","H48W35              ","Computing: Software Development: Graded Unit 2","4","2","BF47","VPG","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","HL9X35","Software Development: Object Oriented Programming - Advanced Concepts","2","1","BF47","VPG","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","HL9W35","Software Development: Web Development Advanced Web Scripting Concepts","1","1","A","Neymar9","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","HL9W35","Software Development: Web Development Advanced Web Scripting Concepts","1","2","A","Neymar9","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","HL9V35","Software Development: Programming Paradigms","2","1","V","Ronal","0","0","0")
,("HDCSD_BF217B","HND Computing: Software Development SCQF Level 8 - Yr2 Grp B","STB","HL9T35","Software Development: Data Structures and Performance","2","2","V","Ronal","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17334              ","Developing Software: Introduction","2","1","A","Maradona","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17534              ","Computer Systems Fundamentals","2","1","A","Zidane","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17734              ","Troubleshooting Computer Problems","2","1","V","Messi","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17834              ","Team Working in Computing","2","2","A","DUMMY","BF44","Thursday","09:00")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17934              ","Cloud Computing","2","2","A","Maradona","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17E34              ","Computing: PC Hardware and Operating System Essentials","2","1","CISCO","Zidane","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17F34              ","Computing: PC Hardware and Operating System Support","2","2","CISCO","Zidane","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H1F734              ","Professionalism and Ethics in Computing","2","1","BS50","Maradona","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H1J834              ","Computing: Graded Unit 1","1","1","A","Zidane","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H1J835","Computing: Graded Unit 1","1","2","A","Zidane","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H1EM34","Client Operating Systems","3","2","V","Cruyff8","BF45A","Tuesday","09:00")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17C34","Computer Networks: Building Local Area Networks","2","1","CISCO","Zidane","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H17C35","Computer Networks: Building Local Area Networks","2","2","CISCO","Zidane","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","HG1K34","Professional Career Development in the IT Industry","2","1","A","Cruyff8","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H1EP34","Ethical Hacking Fundamentals","2","2","V","Zidane","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","DM2X35              ","Computer Operating Systems 2","2","1","V","Cruyff8","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","F1W034              ","Project Management for IT","2","1","BS50","Xavi9","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H17M34              ","Intrusion Prevention Systems","2","2","V","Bob","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H18C35              ","Open Source Operating Systems: Introduction to Command Line Administration","2","2","V","Kaka7","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H1EN34              ","Computer Forensics: Fundamentals","2","1","V","Messi","0","0","0")
,("HDCTS_BF117A"," HND Computing: Technical Support SCQF Level 8 - Yr1 Grp A","STB","H1EM35","Client Operating Systems","1","2","V","NLR","BF45A","Tuesday","12:00")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H3LN35              ","Providing Technical Support to Users","2","2","A","Cruyff8","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H8N535              ","Private Cloud Virtualisation","2","1","V","Pele10","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H16T35              ","Network Server Operating Systems","2","1","V","Cruyff8","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H16T35              ","Network Server Operating Systems","2","2","V","Cruyff8","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H16V35              ","Network Technology and Data Communications","4","1","V","John","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H17V34              ","Security Concepts","2","1","V","Zidane","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H17V34              ","Security Concepts","2","2","V","Zidane","0","0","0")
,("HDCTS_BF217A"," HND Computing: Technical Support SCQF Level 8 - Yr2 Grp A","STB","H48X35              ","Computing: Technical Support: Graded Unit 2","4","2","CISCO","Pele10","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F3GC11              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F3GD11              ","Problem Solving","0","0","0","0","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F18211              ","Computing: Website Design and Development","2","2","A","Pirlo","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F1FC11              ","PC Passport: IT Software - Word Processing and Presenting Information","2","1","A","Kaka7","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F1KB11              ","Computing: Animation Fundamentals","2","1","A","Xavi9","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F1KH11              ","Computing: Computer Networking Fundamentals","2","2","V","Kaka7","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Support, Networking) -Yr1 Grp A","STB","F1KR11              ","Computing: Computer Hardware and Systems","2","1","V","Kaka7","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F1KS11              ","Computing: Digital Media Elements for Applications","2","2","A","Pirlo","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F3GB10              ","Communication","0","0","0","0","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F3GB11              ","Communication","2","0","A","0","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F3GF10              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","F3GF11              ","Numeracy","2","0","A","0","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","H22175              ","Lifeskills Mathematics: Managing Finance and Statistics","0","0","0","0","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","H6S945              ","Computing: Applications Development","2","1","A","Bob","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","SHTML5              ","HTML5 Coding","2","1","A","Pirlo","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","H22375              ","Software Design and Development","3","2","A","Bob","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","H22675              ","Information System Design and Development","3","1","A","Kaka7","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","H6S745              ","Computing: Project","3","2","V","Kaka7","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","SENCH5              ","Enhanced Curriculum Level 5","1","1","A","Cruyff8","0","0","0")
,("NCCDM5_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","STB","SENCH5              ","Enhanced Curriculum Level 5","1","2","A","Cruyff8","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F3GC11              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F3GD11              ","Problem Solving","0","0","0","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F18211              ","Computing: Website Design and Development","2","2","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F1FC11              ","PC Passport: IT Software - Word Processing and Presenting Information","2","1","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F1KB11              ","Computing: Animation Fundamentals","2","1","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F1KH11              ","Computing: Computer Networking Fundamentals","2","2","V","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F1KR11              ","Computing: Computer Hardware and Systems","2","1","V","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F1KS11              ","Computing: Digital Media Elements for Applications","2","2","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F3GB10              ","Communication","0","0","0","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F3GB11              ","Communication","2","0","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F3GF10              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","F3GF11              ","Numeracy","2","0","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","H22175              ","Lifeskills Mathematics: Managing Finance and Statistics","0","0","0","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","H6S945              ","Computing: Applications Development","2","1","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","SHTML5              ","HTML5 Coding","2","1","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","H22375              ","Software Design and Development","3","2","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","H22675              ","Information System Design and Development","3","1","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","H6S745              ","Computing: Project","4","2","V","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","SENCH5              ","Enhanced Curriculum Level 5","1","1","A","0","0","0","0")
,("NCCDM5_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpB","STB","SENCH5              ","Enhanced Curriculum Level 5","1","2","A","0","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F3GC11              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F3GD11              ","Problem Solving","0","0","0","0","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F18211              ","Computing: Website Design and Development","2","2","A","Xavi9","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F1FC11              ","PC Passport: IT Software - Word Processing and Presenting Information","2","1","A","ANO1","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F1KB11              ","Computing: Animation Fundamentals","2","1","A","Xavi9","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F1KH11              ","Computing: Computer Networking Fundamentals","2","2","V","Messi","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F1KR11              ","Computing: Computer Hardware and Systems","2","1","V","Messi","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F1KS11              ","Computing: Digital Media Elements for Applications","2","2","A","Xavi9","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F3GB10              ","Communication","0","0","0","0","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F3GB11              ","Communication","2","1","A","0","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F3GF10              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","F3GF11              ","Numeracy","2","2","A","0","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","H22175              ","Lifeskills Mathematics: Managing Finance and Statistics","0","0","0","0","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","H6S945              ","Computing: Applications Development","2","1","A","Maradona","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","SHTML5              ","HTML5 Coding","2","1","A","Xavi9","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","H22375              ","Software Design and Development","3","2","A","Maradona","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","H22675              ","Information System Design and Development","3","1","A","Maradona","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","H6S745              ","Computing: Project","3","2","V","Kaka7","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","SENHC5","Enhanced Curriculum Level 5","1","1","A","Bob","0","0","0")
,("NCCDM5_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support - Yr1 GrpA","WESTWING","SENHC5","Enhanced Curriculum Level 5","1","2","A","Bob","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F3GC11              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F3GD11              ","Problem Solving","0","0","0","0","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F18211              ","Computing: Website Design and Development","2","2","A","Xavi9","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F1FC11              ","PC Passport: IT Software - Word Processing and Presenting Information","2","1","A","ANO1","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F1KB11              ","Computing: Animation Fundamentals","2","1","A","Xavi9","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F1KH11              ","Computing: Computer Networking Fundamentals","2","2","V","Messi","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F1KR11              ","Computing: Computer Hardware and Systems","2","1","V","Messi","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F1KS11              ","Computing: Digital Media Elements for Applications","2","2","A","Xavi9","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F3GB10              ","Communication","0","0","0","0","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F3GB11              ","Communication","2","1","A","0","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F3GF10              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","F3GF11              ","Numeracy","2","2","A","0","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","H22175              ","Lifeskills Mathematics: Managing Finance and Statistics","0","0","0","0","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","H6S945              ","Computing: Applications Development","2","1","A","Becks","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","SHTML5              ","HTML5 Coding","2","1","A","Xavi9","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","H22375              ","Software Design and Development","3","2","A","Becks","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","H22675              ","Information System Design and Development","3","1","A","ANO1","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","H6S745              ","Computing: Project","3","2","V","Bob","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","SENCH5              ","Enhanced Curriculum Level 5","1","1","A","Bob","0","0","0")
,("NCCDM5_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support Yr1 Grp B","WESTWING","SENCH5              ","Enhanced Curriculum Level 5","1","2","A","Bob","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F3GC11              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F3GD11              ","Problem Solving","0","0","0","0","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F18211              ","Computing: Website Design and Development","2","2","S3.12","Cruyff8"," ","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F1FC11              ","PC Passport: IT Software - Word Processing and Presenting Information","2","1","S3.12","Cruyff8","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F1KB11              ","Computing: Animation Fundamentals","2","1","S3.12","Cruyff8","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F1KH11              ","Computing: Computer Networking Fundamentals","2","2","S3.12","Messi","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F1KR11              ","Computing: Computer Hardware and Systems","2","1","S3.12","Messi","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F1KS11              ","Computing: Digital Media Elements for Applications","2","2","S3.12","Cruyff8","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F3GB10              ","Communication","0","0","0","0","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F3GB11              ","Communication","2","0","S3.12","0","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F3GF10              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","F3GF11              ","Numeracy","2","0","S3.12","0","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","H22175              ","Lifeskills Mathematics: Managing Finance and Statistics","0","0","0","0","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","H6S945              ","Computing: Applications Development","2","1","S3.12","PSG1","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","SHTML5              ","HTML5 Coding","2","1","S3.12","ANO1","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","H22375              ","Software Design and Development","3","2","S3.12","PSG1","S3.12","Wednesday","14:00")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","H22675              ","Information System Design and Development","3","1","S3.12","Cruyff8","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","H6S745              ","Computing: Project","3","2","S3.12","Messi","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","SENCH5              ","Enhanced Curriculum Level 5","1","1","S3.12","Cruyff8","0","0","0")
,("NCCDM5_SF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support -Yr1 Grp A","EASTERN","SENCH5              ","Enhanced Curriculum Level 5","1","2","S3.12","Cruyff8","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F18011              ","Computing: Interactive Multimedia for Website Design","2","2","A","Xavi9","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F3GB11              ","Communication","0","0","0","0","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F3GB12              ","Communication","2","1","A","0","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F3GC12              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F3GD12              ","Problem Solving","0","0","0","0","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F3GF11              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F3GF12              ","Numeracy","2","2","A","0","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F3SY12              ","Computing: Computer Hardware and Systems","2","1","V","John","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","F3T212              ","Computing: Authoring a Website","2","1","A","Xavi9","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","H2TM12              ","Programming for Mobile Devices","2","2","A","Maradona","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","H60C46              ","Computing: Academic Skills","2","1","A","Zidane","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","H6S946              ","Computing: Applications Development","2","1","A","Becks","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","H7EA46              ","Network Literacy","2","1","A","Kaka7","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","H9E246              ","Data Security","2","1","A","Cruyff8","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","H9J046              ","Digital Forensics","2","2","V","Messi","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","SAPPFG              ","Apps for Good","2","1","A","Becks","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","SAPPFG              ","Apps for Good","1","2","A","Becks","BF47","Monday","14:00")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","H22376              ","Software Design and Development","2","2","A","Becks","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","H6S746              ","Computing: Project (Software)","3","2","V","Becks","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","SENCH6              ","Enhanced Curriculum Level 6","1","1","A","Becks","0","0","0")
,("NCCDM6_BF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","STB","SENCH6              ","Enhanced Curriculum Level 6","1","2","A","Becks","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F18011              ","Computing: Interactive Multimedia for Website Design","2","2","A","Xavi9","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F3GB11              ","Communication","0","0","0","0","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F3GB12              ","Communication","2","0","A","0","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F3GC12              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F3GD12              ","Problem Solving","0","0","0","0","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F3GF11              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F3GF12              ","Numeracy","2","0","A","0","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F3SY12              ","Computing: Computer Hardware and Systems","2","1","V","John","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","F3T212              ","Computing: Authoring a Website","2","1","A","Pirlo","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","H2N612              ","Network Fundamentals","2","2","V","John","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","H2N712              ","Server Administration Fundamentals","2","2","V","John","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","H60C46              ","Computing: Academic Skills","2","1","A","Pirlo","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","H6S946              ","Computing: Applications Development","2","1","A","Maradona","BF45","Thursday","14:00")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","H7EA46              ","Network Literacy","2","1","A","Cruyff8","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","H9E246              ","Data Security","2","1","A","Cruyff8","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","H9J046              ","Digital Forensics","2","2","V","Messi","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","SAPPFG              ","Apps for Good","2","1","A","Kaka7","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","SAPPFG              ","Apps for Good","1","2","A","Kaka7","BF45A","Monday","14:00")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","H6S746              ","Computing: Project (Networking)","3","2","V","John","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","SENCH6              ","Enhanced Curriculum Level 6","1","2","A","Becks","0","0","0")
,("NCCDM6_BF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","STB","SENCH6              ","Enhanced Curriculum Level 6","1","1","A","Becks","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F18011              ","Computing: Interactive Multimedia for Website Design","2","2","A","Xavi9","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F3GB11              ","Communication","0","0","0","0","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F3GB12              ","Communication","2","1","A","0","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F3GC12              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F3GD12              ","Problem Solving","0","0","0","0","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F3GF11              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F3GF12              ","Numeracy","2","2","A","0","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F3SY12              ","Computing: Computer Hardware and Systems","2","1","V","Bob","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","F3T212              ","Computing: Authoring a Website","2","1","A","Xavi9","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","H2TM12              ","Programming for Mobile Devices","2","2","A","Maradona","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","H60C46              ","Computing: Academic Skills","2","1","A","ANO2","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","H6S946              ","Computing: Applications Development","2","1","A","Maradona","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","H7EA46              ","Network Literacy","2","1","A","Kaka7","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","H9E246              ","Data Security","2","1","A","Messi","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","H9J046              ","Digital Forensics","2","2","V","Bob","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","SAPPFG              ","Apps for Good","2","1","A","Bob","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","SAPPFG              ","Apps for Good","1","2","A","Bob","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","H22376              ","Software Design and Development","2","2","A","Maradona","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","H6S746              ","Computing: Project","3","2","V","Xavi9","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","SENCH6              ","Enhanced Curriculum Level 6","1","2","A","Xavi9","0","0","0")
,("NCCDM6_HF117A","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp A","WESTWING","SENCH6              ","Enhanced Curriculum Level 6","1","1","A","Xavi9","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F18011              ","Computing: Interactive Multimedia for Website Design","2","2","A","Xavi9","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F3GB11              ","Communication","0","0","0","0","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F3GB12              ","Communication","2","1","A","0","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F3GC12              ","Information and Communication Technology","0","0","0","0","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F3GD12              ","Problem Solving","0","0","0","0","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F3GF11              ","Numeracy","0","0","0","0","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F3GF12              ","Numeracy","2","2","A","0","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F3SY12              ","Computing: Computer Hardware and Systems","2","1","V","Bob","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","F3T212              ","Computing: Authoring a Website","2","1","A","Xavi9","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","H2N612              ","Network Fundamentals","2","2","V","Kaka7","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","H2N712              ","Server Administration Fundamentals","2","2","V","Kaka7","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","H60C46              ","Computing: Academic Skills","2","1","A","ANO1","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","H6S946              ","Computing: Applications Development","2","1","A","Maradona","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","H7EA46              ","Network Literacy","2","1","A","Kaka7","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","H9E246              ","Data Security","2","1","A","Messi","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","H9J046              ","Digital Forensics","2","2","V","Bob","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","SAPPFG              ","Apps for Good","2","1","A","Kaka7","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","SAPPFG              ","Apps for Good","1","2","A","Kaka7","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","H6S746              ","Computing: Project","3","2","V","Xavi9","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","SENCH6              ","Enhanced Curriculum Level 6","1","2","A","Xavi9","0","0","0")
,("NCCDM6_HF117B","NC Computing (Software Development- Mobile Development- Cyber Security- Technical Support) Yr1 Grp B","WESTWING","SENCH6              ","Enhanced Curriculum Level 6","1","1","A","Xavi9","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NPPSD_BF117A","Foundation Apprenticeship","STB","NPPSD (Tues)","Foundation Apprenticeship","1","1","BS50","Maradona","BS50","Tuesday","13:00")
,("NPPSD_BF117A","Foundation Apprenticeship","STB","NPPSD (Tues)","Foundation Apprenticeship","2","2","BS50","Gullit","BS50","Tuesday","13:00")
,("NPPSD_BF117A","Foundation Apprenticeship","STB","NPPSD (Tues)","Foundation Apprenticeship","2","2","BS50","Maradona","BS50","Tuesday","15:00")
,("NPPSD_BF117A","Foundation Apprenticeship","STB","NPPSD (Thurs)","Foundation Apprenticeship","4","1","BS50","NLR","BS50","Thursday","13:00")
,("NPPSD_BF117A","Foundation Apprenticeship","STB","NPPSD (Thurs)","Foundation Apprenticeship","2","2","BS50","NLR","BS50","Thursday","13:00")
,("NPPSD_BF117A","Foundation Apprenticeship","STB","NPPSD (Thurs)","Foundation Apprenticeship","2","2","BS50","Cruyff8","BS50","Thursday","15:00")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("ONCYS5_HP117A","NPA in Cyber Security SCQF Level 5 - Yr1 Grp A","WESTWING","H9J045","Digital Forensics","0","0","0","0","0","0","0")
,("ONCYS5_HP117A","NPA in Cyber Security SCQF Level 5 - Yr1 Grp A","WESTWING","H9HY45","Ethical Hacking / Data Security","0","0","0","0","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("ONCYS6_HP117A","NPA in Cyber Security SCQF Level 6 - Yr1 Grp A","WESTWING","H9J046","Digital Forensics","0","0","0","0","0","0","0")
,("ONCYS6_HP117A","NPA in Cyber Security SCQF Level 6 - Yr1 Grp A","WESTWING","H9HY46","Ethical Hacking / Data Security","0","0","0","0","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("0","0","STB","H17E34","Computing: PC Hardware and Operating System Essentials","2","1","CISCO","Zidane","0","0","0")
,("0","0","STB","H17F34","Computing: PC Hardware and Operating System Support","2","2","CISCO","Zidane","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","H7E944/H7EB44/H22674","Information Literacy/Social Media Literacy/Info System Design + Development","4","2","A","Cruyff8","0","0","0")
,("NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","H6S844","Computing: Creating + Evaluating Software","2","2","A","DUMMY","0","0","0")
,("NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","F1K210/H7EA44","Computing: Computer Hardware + Systems/Network Literacy","3","2","A","Kaka7","0","0","0")
,("NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","F1JM10/H61345","Computing: Digital Media Elements for Applications/Computing:Website Design Fundamentals","3","2","A","Pele10","0","0","0")
,("NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","H6S744/F3GC10","Computing Project/Enhance Curriculum","3","2","A","DUMMY","0","0","0")
,("NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","H1T010","Mobile Technology Systems","2","2","A","Kaka7","0","0","0")
,("NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","H9J044","Digital Forensics","2","2","A","Messi","0","0","0")
,("#NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","F3GC10","Information and Communication Technology (embed in Inform Literacy)","0","2","0","0","0","0","0")
,("#NCCDM4_BF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","STB","F3GD10","Problem Solving (embed in Project)","0","2","0","0","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","H7E944/H7EB44/H22674","Information Literacy/Social Media Literacy/Info System Design + Development","4","2","L1","Cruyff8","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","H6S844","Computing: Creating + Evaluating Software","2","2","L1","DUMMY","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","F1K210/H7EA44","Computing: Computer Hardware + Systems/Network Literacy","3","2","L1","John","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","F1JM10/H61345","Computing: Digital Media Elements for Applications/Computing:Website Design Fundamentals","3","2","L1","DUMMY","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","H6S744/F3GC10","Computing Project/Enhance Curriculum","3","2","L1","Cruyff8","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","H1T010","Mobile Technology Systems","2","2","L1","DUMMY","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","H9J044","Digital Forensics","2","2","L1","Bob","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","F3GC10","Information and Communication Technology (embed in Inform Literacy)","0","2","0","0","0","0","0")
,("NCCDM4_LF117A","NC Computing (Software/Mobile Dev, Cyber Security, Tech Supp, Networking)","SOUTH","F3GD10","Problem Solving (embed in Project)","0","2","0","0","0","0","0")
,("0","0","0","0","0","0","0","0","0","0","0","0")
,("ROOMLOCK","0","0","0","0","3","2","0","0","BS50","Monday","12:00")
,("ROOMLOCK","0","0","0","0","2","2","0","0","BS50","Tuesday","09:00")
,("ROOMLOCK","0","0","0","0","1","2","0","0","BS50","Wednesday","09:00")
,("ROOMLOCK","0","0","0","0","2","2","0","0","BS50","Wednesday","13:00")
,("ROOMLOCK","0","0","0","0","2","2","0","0","BS50","Wednesday","15:00")
,("ROOMLOCK","0","0","0","0","2","2","0","0","BS50","Thursday","09:00")
,("ROOMLOCK","0","0","0","0","1","2","0","0","BS50","Friday","09:00")
,("ROOMLOCK","0","0","0","0","1","2","0","0","BS50","Friday","11:00")
,("ROOMLOCK","0","0","0","0","3","2","0","0","BF47","Thursday","09:00")
,("ROOMLOCK","0","0","0","0","2","2","0","0","H1.08","Monday","14:00")
,("ROOMLOCK","0","0","0","0","3","2","0","0","H1.08","Wednesday","13:00")
,("ROOMLOCK","0","0","0","0","2","2","0","0","S3.12","Monday","11:00")
,("ROOMLOCK","0","0","0","0","4","2","0","0","S3.12","Thursday","09:00")
,("ROOMLOCK","0","0","0","0","8","2","0","0","L1","Friday","09:00")
,("#######ROOMLOCK","0","0","0","0","2","2","0","0","L1","Monday","14:00")
,("#####ROOMLOCK","0","0","0","0","3","2","0","0","L1","Tuesday","13:00")
;
